apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-head
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-head
  template:
    metadata:
      labels:
        app: elasticsearch-head
    spec:
      containers:
        - name: elasticsearch-head
          image: mobz/elasticsearch-head:5
---
apiVersion: v1  # 资源版本
kind: Service  # 资源类型
metadata: # 元数据
  name: elasticsearch-head # 资源名称
spec: # 描述
  selector: # 标签选择器，用于确定当前service代理哪些pod
    app: elasticsearch-head
  type: ClusterIP # service类型
  ports: # 端口信息
    - protocol: TCP
      name: elasticsearch-head
      port: 9100  # service端口
      targetPort: 9100 # pod端口
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dc-es
spec:
  ingressClassName: nginx
  rules:
    - host: dc-es.seasungame.com
      http:
        paths:
          - backend:
              service:
                name: elasticsearch-head
                port:
                  number: 9100
            path: /
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dc-es-filter
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: dc-es.seasungame.com
      http:
        paths:
          - path: /master
            backend:
              service:
                name: elasticsearch-master
                port:
                  number: 9200
            pathType: Prefix